import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import img2 from "../src/assets/nft1.webp";
import img1 from "../src/assets/nft2.webp";
import img3 from "../src/assets/nft3.webp";
import image from "../src/assets/collage2.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <main className={styles.hero}>
          <div className={styles.section}>
            <h2>Buy, Sell & Trade Fractional NFTs</h2>
            <span>
              Mint NFT as a proof for your digital artwork in simple steps and
              sell it in form of fractions directly on the platform to earn from
              it. Token Holders earn a profit by holding the tokens for a peroid
              of time
            </span>
            <div className={styles.buttons}>
              <button className={styles.btn}>Create Listing</button>
              <button className={styles.btn2}>Marketplace</button>
            </div>
          </div>
          <div className={styles.image}>
            <Image className={styles.image} src={image} />
          </div>
        </main>
        <div>
          <li>
            {" "}
            - Mint Digital Proof as NFT for your Artwork for free in under 60
            secs
          </li>
          <li>- All assets stored on decentralized storage like IPFS </li>
          <li>- Control the Sale of NFT and tokens for your artwork</li>
          <li>- Own a art piece , NFT just for fractions of the cost </li>
          <li>
            - Buy tokens/fractions of the NFTs and NFTs at the same platform
          </li>
          <li>
            - Earn a wholesome profit from holding tokens for a short period of
            time
          </li>
        </div>
      </div>
    </div>
  );
}
