import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import video from "../src/assets/3-bg.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
      <main className={styles.hero}>
        <div className={styles.s}>
          <h1>Buy, Sell & Trade Fractional NFTs</h1>
          <span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus, ipsa! Illum </span>
        </div>
        <div className={styles.image}>
          <Image src={video} />
        </div>
      </main>
      </div>
    </div>
  );
}
