import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import video from "../src/assets/8.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h2>artist3</h2>
          <div className={styles.video}>
            <Image src={video} />
            {/* <video autoPlay loop muted className="absolute inset-0 object-cover h-screen xl:h-auto">
            <source
              src="https://cdn.dribbble.com/users/1012997/screenshots/17411811/media/4b36be839ef0103e15ca5025b5903b40.mp4"
              type="video/mp4"
            />
          </video> */}
          </div>
        </div>
      </main>
    </div>
  );
}
